- name: variables
  hosts: localhost
  vars:
   Topic: ansible
   Duration: 10 hours
  tasks:
  - name: print information
    ansible.builtin.debug:
     msg: "Hi, I am learning {{Topic}}, duration is {{Duration}}."