- name: Variables from files
  hosts: localhost
  vars_files:
   - vars.yaml
  tasks:
  - name: print information
    ansible.builtin.debug:
     msg: "Hello, I am practicing {{Course}}, trainer is {{Trainer}} and Duration is {{Duration}}" 