- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    vars:
     Timings: "9:30am to 11:30am and 2:00pm to 6:00pm"
     ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Practitioner{{Practitioner}}, duration is {{Duration}}, timings are{{Timings}}"
   
